spring:
  datasource:
    password: AHdms520
    username: root
    url: jdbc:mysql://192.168.6.129:3306/omp_user?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.6.129
#    password:
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:sqlMapperXml/*.xml